// <auto-generated />
using Asp_Labb3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp_Labb3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240429202853_setup")]
    partial class setup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asp_Labb3.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Asp_Labb3.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Asp_Labb3.Models.UserInterest", b =>
                {
                    b.Property<int>("UserInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserInterestId"));

                    b.Property<int>("FkInterestId")
                        .HasColumnType("int");

                    b.Property<int>("FkUserId")
                        .HasColumnType("int");

                    b.HasKey("UserInterestId");

                    b.HasIndex("FkInterestId");

                    b.HasIndex("FkUserId");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("Asp_Labb3.Models.WebLink", b =>
                {
                    b.Property<int>("WebLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebLinkId"));

                    b.Property<int>("FkInterestId")
                        .HasColumnType("int");

                    b.Property<int>("FkUserId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebLinkId");

                    b.HasIndex("FkInterestId");

                    b.HasIndex("FkUserId");

                    b.ToTable("WebLinks");
                });

            modelBuilder.Entity("Asp_Labb3.Models.UserInterest", b =>
                {
                    b.HasOne("Asp_Labb3.Models.Interest", "Interest")
                        .WithMany("UserInterests")
                        .HasForeignKey("FkInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asp_Labb3.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Asp_Labb3.Models.WebLink", b =>
                {
                    b.HasOne("Asp_Labb3.Models.Interest", "Interest")
                        .WithMany("WebLinks")
                        .HasForeignKey("FkInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asp_Labb3.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("FkUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Asp_Labb3.Models.Interest", b =>
                {
                    b.Navigation("UserInterests");

                    b.Navigation("WebLinks");
                });

            modelBuilder.Entity("Asp_Labb3.Models.User", b =>
                {
                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
